; PaperS3 微信读书阅读器固件
; 基于 M5ReadPaper 的 PaperS3 编译配置（已验证可用），网络层按 weread.koplugin 协议实现

[env:PaperS3]
platform = espressif32@6.13.0
board = esp32-s3-devkitm-1
framework = arduino, espidf
board_build.partitions = full_16MB.csv
board_upload.flash_size = 16MB
board_build.filesystem = spiffs
board_upload.maximum_size = 16777216
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.arduino.memory_type = qio_opi
build_type = debug

build_flags =
    -DCONFIG_EPD_DISPLAY_TYPE_ED047TC1
    -DCONFIG_EPD_BOARD_REVISION_V6
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=4
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DUSE_SD_MMC
    -DARDUINO_M5STACK_PAPER_S3
    -DPNG_MAX_BUFFERED_PIXELS=8642
    -std=c++17
    -O2
    -fexceptions
    -Iinclude
    -fdata-sections
    -ffunction-sections
build_unflags =
    -Os
    -fno-exceptions
    -Werror=format
    -Wunused-but-set-variable

lib_deps =
    m5stack/M5Unified@0.2.14
    m5stack/M5GFX@0.2.20
    bblanchon/ArduinoJson@^7.2.1
    bodmer/TJpg_Decoder@^1.1.0
    bitbank2/PNGdec@^1.1.6
    bitbank2/unzipLIB@^1.0.0
    bitbank2/AnimatedGIF@^2.2.3
